### PR TITLE
Update json-validate.yml

### PR DESCRIPTION
**Pull request by webdev03**

### CODE REVIEW

**Review by hello-smile6 — COMMENTED** [review]
Okay, will this support having multiple workflows? Or will I create one repo for each workflow?

**Comment by webdev03** [comment]
One repo, I think...

**Comment by webdev03** [comment]
WAIT you can have multiple.

**Comment by webdev03** [comment]
Can you merge? Tested, works @hello-smile6

**Comment by webdev03** [comment]
Just remove the `ci` folder after you have merged.

**Comment by hello-smile6** [comment]
> WAIT you can have multiple. But they have to all run at the same time I guess.

Huh. Could I do a `repo-name.txt` file on each repo?

**Review by hello-smile6 — APPROVED** [review]

**Comment by hello-smile6** [comment]
Why delete the branch?

**Comment by webdev03** [comment]
It's my fork. I do what I do on my fork.

**Comment by hello-smile6** [comment]
> It's my fork. I do what I do on my fork.

Okay. Personally, I keep branches.

**Comment by hello-smile6** [comment]
@webdev03 I think I should redo the validation script using JS and put it in this repo.

**Comment by webdev03** [comment]
@hello-smile6 If you want

**Pull request merged**
